import type { Metadata } from "next"
import { notFound } from "next/navigation"
import { createClient } from "@/lib/supabase/server"
import { Navigation } from "@/components/navigation"
import { Footer } from "@/components/footer"
import { ReportView } from "@/components/report/ReportView"
import { PendingClient } from "@/components/report/PendingClient"
import { ShareControls } from "@/components/report/ShareControls"
import { HistorySync } from "@/components/report/HistorySync"
import { ReportProvider } from "@/contexts/report-context"
import { Analysis } from "@/lib/ai/schema"

const UUID_RE =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i

type Report = {
  id: string
  status: "pending" | "analyzing" | "ready" | "failed"
  file_name: string
  file_size: number
  mime_type: string
  storage_path: string
  duration_seconds: number | null
  analysis: unknown
  error_message: string | null
  created_at: string
}

/**
 * Per-report metadata. Drives the social card unfurl on Twitter/LinkedIn/
 * Slack/Discord. The OG image itself is generated by the colocated
 * opengraph-image.tsx — Next.js wires it in automatically when this
 * route exports generateMetadata.
 */
export async function generateMetadata({
  params,
}: {
  params: Promise<{ id: string }>
}): Promise<Metadata> {
  const { id } = await params
  const baseTitle = "METRIC.fyi · Virality Report"
  const baseDesc =
    "The brutally honest reason your video isn't going off — 0–100 score with timestamped feedback."

  if (!UUID_RE.test(id)) {
    return { title: baseTitle, description: baseDesc }
  }

  try {
    const supabase = await createClient()
    const { data } = await supabase
      .rpc("fetch_report", { p_id: id })
      .single<Report>()

    if (!data?.id || data.status !== "ready" || !data.analysis) {
      return { title: baseTitle, description: baseDesc }
    }

    const parsed = Analysis.safeParse(data.analysis)
    if (!parsed.success) return { title: baseTitle, description: baseDesc }

    const a = parsed.data
    const title = `${a.score}/100 · METRIC.fyi`
    const description =
      a.verdict.length > 200 ? a.verdict.slice(0, 197) + "…" : a.verdict

    return {
      title,
      description,
      openGraph: {
        title,
        description,
        type: "website",
        siteName: "METRIC.fyi",
      },
      twitter: {
        card: "summary_large_image",
        title,
        description,
      },
    }
  } catch {
    return { title: baseTitle, description: baseDesc }
  }
}

export default async function ReportPage({
  params,
}: {
  params: Promise<{ id: string }>
}) {
  const { id } = await params
  if (!UUID_RE.test(id)) notFound()

  const supabase = await createClient()
  const { data, error } = await supabase
    .rpc("fetch_report", { p_id: id })
    .single<Report>()

  if (error || !data || !data.id) notFound()

  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
  const videoUrl = `${supabaseUrl}/storage/v1/object/public/videos/${data.storage_path}`

  const initialAnalysis =
    data.status === "ready" && data.analysis
      ? Analysis.parse(data.analysis)
      : null

  return (
    <main
      className="flex flex-col min-h-screen"
      style={{ background: "var(--color-ink)", color: "var(--color-text)" }}
    >
      <Navigation />

      {/* Sub-nav status strip — sits just below the main nav, hugs the brand */}
      <div
        className="border-b px-6 md:px-14 py-3 flex flex-wrap items-center gap-3"
        style={{ borderColor: "var(--color-line)" }}
      >
        <div
          className="flex items-center gap-2.5"
          style={{
            fontFamily: "var(--font-mono)",
            fontSize: 11,
            color: "var(--color-text-dim)",
            letterSpacing: "0.1em",
          }}
        >
          <span>REPORT · /r/{data.id.slice(0, 6)}</span>
          <span style={{ color: "var(--color-line)" }}>·</span>
          <span
            className="inline-flex items-center gap-1.5"
            style={{
              color:
                data.status === "ready"
                  ? "var(--color-signal)"
                  : data.status === "failed"
                    ? "var(--color-hot)"
                    : "var(--color-text-dim)",
            }}
          >
            {data.status === "ready" && (
              <span
                style={{
                  width: 6,
                  height: 6,
                  background: "var(--color-signal)",
                  borderRadius: "50%",
                  display: "inline-block",
                }}
              />
            )}
            {data.status.toUpperCase()}
          </span>
        </div>
        <span
          className="hidden md:inline truncate"
          style={{
            fontFamily: "var(--font-mono)",
            fontSize: 10,
            color: "var(--color-text-mute)",
            letterSpacing: "0.05em",
            maxWidth: 320,
          }}
          title={data.file_name}
        >
          {data.file_name}
        </span>

        {data.status === "ready" && initialAnalysis && (
          <ShareControls
            shareUrl={`https://metric-fyi.vercel.app/r/${data.id}`}
            score={initialAnalysis.score}
            verdict={initialAnalysis.verdict}
          />
        )}
      </div>

      <ReportProvider initialAnalysis={initialAnalysis}>
        {data.status === "ready" && initialAnalysis ? (
          <ReportView videoUrl={videoUrl} />
        ) : data.status === "failed" ? (
          <FailedState message={data.error_message ?? "Unknown error"} />
        ) : (
          <PendingClient id={data.id} videoUrl={videoUrl} />
        )}
      </ReportProvider>

      {/* Update local history entry (if any) — only touches entries the
          user created via upload. No-op when there's no matching entry. */}
      <HistorySync
        id={data.id}
        status={data.status}
        score={initialAnalysis?.score}
        category={initialAnalysis?.comparison.inferredCategory}
      />

      <Footer />
    </main>
  )
}

function FailedState({ message }: { message: string }) {
  return (
    <div className="max-w-[1280px] mx-auto px-6 md:px-14 pt-12 pb-24">
      <div
        style={{
          fontFamily: "var(--font-mono)",
          fontSize: 11,
          color: "var(--color-hot)",
          letterSpacing: "0.2em",
        }}
      >
        ANALYSIS FAILED
      </div>
      <h1
        className="mt-3 font-semibold"
        style={{
          fontFamily: "var(--font-display)",
          fontSize: "clamp(40px, 6vw, 72px)",
          lineHeight: 0.98,
          letterSpacing: "-0.025em",
        }}
      >
        Something went wrong on this video.
      </h1>
      <p
        className="mt-4 max-w-[640px]"
        style={{
          fontFamily: "var(--font-mono)",
          fontSize: 12,
          color: "var(--color-text-dim)",
        }}
      >
        {message}
      </p>
    </div>
  )
}
